### PR TITLE
Rename pyasdf to asdf

### PR DESCRIPTION
**Pull request by olebole**
This includes the renaming of the python package as well as the upcoming renaming of its github repository.

### CODE REVIEW

**Comment by nden** [comment]
@olebole Could you add `caption` to this line? I hope it fixes the travis error.

https://github.com/olebole/asdf-standard/blob/rename-pyasdf-to-asdf/install-texlive.sh#L15

**Comment by olebole** [comment]
Sure, I did, but it has nothing to do with the rename...

**Comment by olebole** [comment]
This didn't help. Maybe you fix this independently of the rename?

**Comment by nden** [comment]
Agreed this isn't relevant for this PR.

**Comment by nden** [comment]
I opened a new issue for the problem with travis-ci and will merge this.

**Pull request merged**
